### ISSUE TITLE
Reuse docker build in Hive jobs.

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_rust#1008]
Currently, we're building our docker image for each Hive job. Instead, we should reuse the image from `docker-build`. 

See: https://docs.docker.com/build/ci/github-actions/share-image-jobs/

Instead of using `make run-hive`, that depends on `build-image`, we should run hive directly.

**Comment by rodrigo-o** [comment]
This is also true for assertoor!
