### ISSUE TITLE
[L1] Validate blobs when adding a blob transaction to the mempool

### ISSUE THREAD

**Issue by fmoletta** [lambdaclass/lambda_ethereum_rust#1054]
Currently when adding a blob transaction to the mempool, we are only checking that the amount of blobs matches the amount of blob versioned hashes in the transaction. We should also hash the blobs and check that they match the blob versioned hahses in the transaction.
This should be added to the `validate_blobs_bundle` function in the mempool module ([here](https://github.com/lambdaclass/lambda_ethereum_rust/blob/f00cbfb22c706fafb121944420ef129306392dc7/crates/blockchain/mempool.rs#L202))

**Comment by h3lio5** [comment]
is it preferred to impl the sha256 function in the `blockchain` crate or import it from `networking/p2p/rlpx/utils.rs`?

Additionally, the EIP4844 spec mentions to verify `kzg commitment` against the `blob`, `proof` using the `verify_blob_kzg_proof_batch()` method. Should we do it in the `validate_blobs_bundle()` function or is it not necessary for mempool filtering but only needed during full block verification?
