### ISSUE TITLE
Multiplex between capabilities according to msg-id

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_rust#171]
See https://github.com/ethereum/devp2p/blob/master/rlpx.md#message-id-based-multiplexing

After each node sends its supported capabilities in the Hello message, the message ID space is defined based on the shared capabilities.

**Comment by ElFantasma** [comment]
I believe this was solved in the [messages.rs](https://github.com/lambdaclass/lambda_ethereum_rust/blob/main/crates/networking/p2p/rlpx/message.rs#L21-L41) module. I'm closing it, but we may reopen it or create a new one in case we are missing something
