### ISSUE TITLE
Test block building with a Kurtosis localnet

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_rust#674]
Spawn a localnet with a validator node that uses ethereum_rust as an execution client.

We should test that block building is working properly (even if there are no transactions since we don't support P2P txs, but maybe there are some sent through RPC).

**Comment by mpaulucci** [comment]
Investigate this tool: https://github.com/ethpandaops/assertoor/tree/master

**Comment by rodrigo-o** [comment]
This should be already solved by: #952 and #953
