### ISSUE TITLE
Improve error handling in RLPx modules

### ISSUE THREAD

**Issue by ElFantasma** [lambdaclass/lambda_ethereum_rust#845]
Currently RLPx code is plagued with `unwrap()`s and it panics whenever it finds an error. We should:

- Change most functions returning results to `Result` type to allow failure
- Build an Error enum to wrap most RLPx errors
- Handle most errors. (decide whether we should panic, log, ignore, etc. on each one)

**Comment by fkrause98** [comment]
Just for the record: the RLPx code also has a lot of slicing, but we're not doing the proper bounds checking, something to keep in mind for error handling.
