### ISSUE TITLE
feat(EIP4844 TX): Implement custom Deserialization trait

### ISSUE THREAD

**Issue by fborello-lambda** [lambdaclass/lambda_ethereum_rust#882]
We have implemented a custom `Deserialization` for all transaction types,  except for `TxType::EIP4844`.
[CodeLine](https://github.com/lambdaclass/ethereum_rust/blob/408e256096ab96b971d9843b0c3f9a5dfaef9a2b/crates/common/types/transaction.rs#L1103)

**Comment by h3lio5** [comment]
can I take this issue please? After having a quick look at the code, this issue seems straightforward.
