### ISSUE TITLE
Hive tests for P2P "snap" capability

### ISSUE THREAD

**Issue by fmoletta** [lambdaclass/lambda_ethereum_rust#934]
[Hive Test Suite](https://github.com/ethereum/go-ethereum/blob/a5fe7353cff959d6fcfcdd9593de19056edb9bdb/cmd/devp2p/internal/ethtest/suite.go#L87)
[Capability doc](https://github.com/ethereum/devp2p/blob/master/caps/snap.md)

Tests:

- [x] Status #960 
- [x] AccountRange #960
- [x] GetByteCodes #1028 
- [x] GetTrieNodes #1031 
- [x] GetStorageRanges #1025

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
