### ISSUE TITLE
Add an allowedPrivilegedTransactions list to the L1 contract that keeps track of deposits made by users

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/lambda_ethereum_rust#977]
To make sure the operator can't lie and include invalid deposit transactions, the L1 contracts needs to keep a queue of every deposit/PrivilegedTransaction that is sent to it.

The operator must take all the deposits it processed in a block, hash them together and include that as a public input to the proof.

L1 onchain operator will then, after verifying a new block, pop from the queue as many deposits as were made on L2, then hash them and make sure the hash matches the one passed as public inputs. If it does not match, the L2 block is rejected; if it matches, the block is valid and everything proceeds as normal

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
